<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>CopycatDb.Nuzzle</PackageId>
    <Version>0.1.0</Version>
    <Authors>CopycatDb</Authors>
    <Description>High-performance ADO.NET provider for SQL Server powered by tabby (Rust TDS)</Description>
    <RepositoryUrl>https://github.com/copycatdb/nuzzle</RepositoryUrl>
    <License>MIT</License>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
